ALTER TABLE "FoodEntry" ADD COLUMN IF NOT EXISTS "saturatedFatG" INTEGER;
ALTER TABLE "FoodEntry" ADD COLUMN IF NOT EXISTS "fiberG" INTEGER;
ALTER TABLE "FoodEntry" ADD COLUMN IF NOT EXISTS "sugarG" INTEGER;
ALTER TABLE "FoodEntry" ADD COLUMN IF NOT EXISTS "addedSugarG" INTEGER;
ALTER TABLE "FoodEntry" ADD COLUMN IF NOT EXISTS "sodiumMg" INTEGER;
ALTER TABLE "FoodEntry" ADD COLUMN IF NOT EXISTS "cholesterolMg" INTEGER;
ALTER TABLE "FoodEntry" ADD COLUMN IF NOT EXISTS "serving" TEXT NOT NULL DEFAULT '';
