/** Starter cleanse list: keto carbs, low-fat proteins. No bacon / fatty cuts. */

export type GrocerySeedRow = {
  name: string;
  aliases: string;
  category: string;
  whyGood: string;
  whyAvoid: string;
  sortOrder: number;
};

export const APPROVED_GROCERY_SEED: GrocerySeedRow[] = [
  {
    name: "Chicken breast",
    aliases:
      "chicken breasts, boneless skinless chicken, chicken tenderloins, chicken tenders, chicken thighs, chicken thigh, fried chicken",
    category: "protein",
    whyGood: "Lean protein that keeps you full on the cleanse without a fat load.",
    whyAvoid: "Wings, thighs with skin, and fried chicken pile on fat and breading Jeremy does not want for 3 months.",
    sortOrder: 10,
  },
  {
    name: "Turkey breast",
    aliases: "sliced turkey, deli turkey, turkey cutlets, roast turkey",
    category: "protein",
    whyGood: "Very lean, easy lunch protein. Use instead of processed lunch meats.",
    whyAvoid: "Bacon, turkey bacon, and sausage are still fatty processed meats — they stay off this list.",
    sortOrder: 20,
  },
  {
    name: "93% lean ground turkey",
    aliases:
      "ground turkey 93/7, 93/7 ground turkey, lean ground turkey, 99% ground turkey, extra lean turkey, 80/20, 80/20 beef, ground beef, hamburger meat, chuck",
    category: "protein",
    whyGood: "High protein, low fat — the cleanse burger / taco meat.",
    whyAvoid: "80/20 beef, 85/15 turkey, and regular ground pork carry the fat we are cutting.",
    sortOrder: 30,
  },
  {
    name: "93% lean ground chicken",
    aliases: "ground chicken 93, lean ground chicken",
    category: "protein",
    whyGood: "Same job as lean turkey — chili, lettuce tacos, meat sauce without the grease.",
    whyAvoid: "Regular ground chicken often includes skin and fat. Check the label.",
    sortOrder: 40,
  },
  {
    name: "Pork tenderloin",
    aliases: "pork loin, pork filet",
    category: "protein",
    whyGood: "The lean cut of pork. Season and roast.",
    whyAvoid: "Bacon, pork belly, ribs, and sausage are extra-fatty cuts — not on Jeremy’s list.",
    sortOrder: 50,
  },
  {
    name: "Sirloin steak",
    aliases: "top sirloin, sirloin tip, lean steak, ribeye, t-bone, tbone, brisket, fatty steak",
    category: "protein",
    whyGood: "A lean beef option when you want a steak night without the marble.",
    whyAvoid: "Ribeye, T-bone, brisket, and 80/20 chuck are fatty cuts. Save those for a later desire meal.",
    sortOrder: 60,
  },
  {
    name: "Eye of round",
    aliases: "bottom round, top round, round roast, london broil",
    category: "protein",
    whyGood: "The leanest roast/steak family. Slice thin after cooking.",
    whyAvoid: "Fatty roasts and short ribs undo the cleanse.",
    sortOrder: 70,
  },
  {
    name: "Cod",
    aliases: "atlantic cod, pacific cod, white fish, baked fish",
    category: "protein",
    whyGood: "Almost no fat, lots of protein. Pan or oven.",
    whyAvoid: "Battered fish and fish sticks are a fried-carb trap.",
    sortOrder: 80,
  },
  {
    name: "Tilapia",
    aliases: "tilapia fillets",
    category: "protein",
    whyGood: "Cheap, lean white fish for weeknights.",
    whyAvoid: "Skip the frozen fried patties.",
    sortOrder: 90,
  },
  {
    name: "Halibut",
    aliases: "halibut steak",
    category: "protein",
    whyGood: "Lean, filling white fish.",
    whyAvoid: "Don’t deep-fry it.",
    sortOrder: 100,
  },
  {
    name: "Shrimp",
    aliases: "prawns, cocktail shrimp, raw shrimp",
    category: "protein",
    whyGood: "High protein, almost no fat. Sauté with spices, not butter baths.",
    whyAvoid: "Breaded popcorn shrimp is a fried-carb bomb.",
    sortOrder: 110,
  },
  {
    name: "Scallops",
    aliases: "sea scallops, bay scallops",
    category: "protein",
    whyGood: "Lean, fast-cook protein.",
    whyAvoid: "Bacon-wrapped scallops put bacon back on the plate — leave the bacon off.",
    sortOrder: 120,
  },
  {
    name: "Tuna in water",
    aliases: "canned tuna, tuna pouch, albacore in water, skipjack",
    category: "protein",
    whyGood: "Pantry protein with almost no fat when packed in water.",
    whyAvoid: "Tuna in oil and spicy mayo kits add the fat and sugar we are dropping.",
    sortOrder: 130,
  },
  {
    name: "Salmon",
    aliases: "salmon fillet, atlantic salmon, sockeye",
    category: "protein",
    whyGood: "The one richer fish we keep — omega-3s, 1–2 times a week, not every night.",
    whyAvoid: "This is not permission for ribeye or bacon. Those fats are a different story.",
    sortOrder: 140,
  },
  {
    name: "Egg whites",
    aliases: "liquid egg whites, egg white carton",
    category: "protein",
    whyGood: "Pure protein for omelets and scrambles on the cleanse.",
    whyAvoid: "A 4-yolk omelet with cheese and bacon is a fat stack. Whites first.",
    sortOrder: 150,
  },
  {
    name: "Eggs",
    aliases: "whole eggs, dozen eggs, large eggs",
    category: "protein",
    whyGood: "Whole eggs are fine in small numbers (1–2) with extra whites.",
    whyAvoid: "Don’t build breakfast around yolks, cheese, and fatty meat.",
    sortOrder: 160,
  },
  {
    name: "Nonfat Greek yogurt",
    aliases: "0% greek yogurt, fat free greek yogurt, fage 0, plain greek yogurt",
    category: "dairy",
    whyGood: "Protein snack without the cream. Plain only.",
    whyAvoid: "Full-fat flavored yogurt is sugar plus fat. Not cleanse food.",
    sortOrder: 170,
  },
  {
    name: "1% cottage cheese",
    aliases: "low fat cottage cheese, fat free cottage cheese",
    category: "dairy",
    whyGood: "Slow protein, low fat. Good with cucumber or berries.",
    whyAvoid: "4% / whole-milk cottage cheese is the fatty version.",
    sortOrder: 180,
  },
  {
    name: "Spinach",
    aliases: "baby spinach, spinach box",
    category: "veg",
    whyGood: "Volume food, almost no carbs. Fill the plate.",
    whyAvoid: "Creamed spinach undoes it.",
    sortOrder: 200,
  },
  {
    name: "Kale",
    aliases: "tuscan kale, baby kale",
    category: "veg",
    whyGood: "Same job as spinach — bulk and micronutrients.",
    whyAvoid: "Kale chips in oil-heavy bags can sneak in junk oil.",
    sortOrder: 210,
  },
  {
    name: "Broccoli",
    aliases: "broccoli crowns, broccoli florets",
    category: "veg",
    whyGood: "Fiber + volume. Steam or roast without drowning in oil.",
    whyAvoid: "Cheese sauce broccoli is a different food.",
    sortOrder: 220,
  },
  {
    name: "Cauliflower",
    aliases:
      "cauliflower head, cauliflower florets, riced cauliflower, cauliflower rice, rice, white rice, brown rice, mashed potatoes, potatoes, potato",
    category: "veg",
    whyGood: "This is the rice, mash, and pizza-crust stand-in for the cleanse.",
    whyAvoid: "White rice, potatoes, and pasta are the starches we are pausing.",
    sortOrder: 230,
  },
  {
    name: "Zucchini",
    aliases: "courgette, zucchini noodles, zoodles, pasta, spaghetti, noodles, macaroni",
    category: "veg",
    whyGood: "Noodle swap. Spiralize instead of pasta.",
    whyAvoid: "Pasta, ramen, and boxed mac stay off.",
    sortOrder: 240,
  },
  {
    name: "Asparagus",
    aliases: "asparagus spears",
    category: "veg",
    whyGood: "Nearly zero carb, easy roast veg.",
    whyAvoid: "Don’t wrap it in bacon.",
    sortOrder: 250,
  },
  {
    name: "Cucumber",
    aliases: "english cucumber, mini cucumbers, chips, potato chips, doritos, pretzels, crackers",
    category: "veg",
    whyGood: "Crunch instead of chips.",
    whyAvoid: "Chips, crackers, and pretzels are the snack we are replacing.",
    sortOrder: 260,
  },
  {
    name: "Celery",
    aliases: "celery sticks, celery bunch",
    category: "veg",
    whyGood: "Crunch + volume. Pair with mustard or salsa, not peanut-butter cups.",
    whyAvoid: "Skip the sugary dips.",
    sortOrder: 270,
  },
  {
    name: "Bell peppers",
    aliases: "red pepper, green pepper, yellow pepper, mini peppers",
    category: "veg",
    whyGood: "Color, crunch, low carb. Use as chips.",
    whyAvoid: "Not stuffed with rice and fatty sausage.",
    sortOrder: 280,
  },
  {
    name: "Mushrooms",
    aliases: "baby bella, cremini, white mushrooms, portobello",
    category: "veg",
    whyGood: "Umami and bulk for egg whites and turkey.",
    whyAvoid: "Don’t sauté them in a stick of butter.",
    sortOrder: 290,
  },
  {
    name: "Lettuce",
    aliases:
      "romaine, iceberg, butter lettuce, lettuce wraps, salad mix, spring mix, buns, hamburger buns, bread, sandwich bread, tortillas, wraps",
    category: "veg",
    whyGood: "This is the bun and the wrap. Burgers go in lettuce.",
    whyAvoid: "Bread, buns, tortillas, and wraps are off for the 3-month cleanse.",
    sortOrder: 300,
  },
  {
    name: "Cabbage",
    aliases: "green cabbage, red cabbage, slaw mix",
    category: "veg",
    whyGood: "Cheap volume. Slaw without sugary dressing.",
    whyAvoid: "Creamy bottled coleslaw is sugar + fat.",
    sortOrder: 310,
  },
  {
    name: "Green beans",
    aliases: "string beans, french beans",
    category: "veg",
    whyGood: "Simple side. Steam them.",
    whyAvoid: "Green bean casserole is a holiday fat bomb.",
    sortOrder: 320,
  },
  {
    name: "Brussels sprouts",
    aliases: "brussel sprouts",
    category: "veg",
    whyGood: "Roast with a light spray of oil and spices.",
    whyAvoid: "Not fried and not glazed in honey.",
    sortOrder: 330,
  },
  {
    name: "Avocado",
    aliases: "hass avocado, avocados",
    category: "fat",
    whyGood: "The cleanse fat we do want — fiber and potassium. Half at a time.",
    whyAvoid: "This does not unlock bacon grease or extra-fatty steaks.",
    sortOrder: 400,
  },
  {
    name: "Olive oil",
    aliases: "extra virgin olive oil, evoo",
    category: "fat",
    whyGood: "A teaspoon to cook veg, not a pour.",
    whyAvoid: "Bottled creamy dressings and fried oil baths.",
    sortOrder: 410,
  },
  {
    name: "Strawberries",
    aliases: "fresh strawberries, strawberry",
    category: "fruit",
    whyGood: "Small-portion fruit on keto-style cleanse. Measure a handful.",
    whyAvoid: "Bananas, grapes, mango, and juice spike sugar the cleanse is cutting.",
    sortOrder: 500,
  },
  {
    name: "Blueberries",
    aliases: "fresh blueberries, blueberry",
    category: "fruit",
    whyGood: "Same rule — a small handful, not a bowl.",
    whyAvoid: "Fruit juice and dried sweetened berries.",
    sortOrder: 510,
  },
  {
    name: "Raspberries",
    aliases: "fresh raspberries",
    category: "fruit",
    whyGood: "Highest fiber berry. Small serving.",
    whyAvoid: "Berry pies and syrups.",
    sortOrder: 520,
  },
  {
    name: "Blackberries",
    aliases: "fresh blackberries",
    category: "fruit",
    whyGood: "Low sugar, high fiber. Small serving.",
    whyAvoid: "Smoothie shops dumping juice and sherbet.",
    sortOrder: 530,
  },
  {
    name: "Sparkling water",
    aliases:
      "la croix, topo chico, soda water, seltzer, unsweetened sparkling, soda, coke, pepsi, sprite, juice, fruit juice",
    category: "drink",
    whyGood: "The soda swap. Bubbles without sugar.",
    whyAvoid: "Coke, juice, energy drinks, and sweet tea.",
    sortOrder: 600,
  },
  {
    name: "Black coffee",
    aliases: "coffee beans, ground coffee, espresso",
    category: "drink",
    whyGood: "Fine on the cleanse. No sugar, no flavored creamers.",
    whyAvoid: "Mocha, sweet cream, and blended coffee drinks.",
    sortOrder: 610,
  },
  {
    name: "Unsweetened almond milk",
    aliases:
      "almond milk unsweetened, unsweetened almond, whole milk, 2% milk, oat milk, chocolate milk",
    category: "drink",
    whyGood: "Milk swap with almost no sugar or fat.",
    whyAvoid: "Whole milk, oat milk, and sweetened almond milk.",
    sortOrder: 620,
  },
  {
    name: "Water",
    aliases: "bottled water, sparkling mineral water",
    category: "drink",
    whyGood: "Default drink. Fill it before you shop the aisle.",
    whyAvoid: "Soda and juice are the first things to leave in the store.",
    sortOrder: 630,
  },
  {
    name: "Mustard",
    aliases: "yellow mustard, dijon, spicy brown mustard",
    category: "pantry",
    whyGood: "Flavor with no sugar (check the label).",
    whyAvoid: "Ketchup, BBQ sauce, and honey mustard are sugar.",
    sortOrder: 700,
  },
  {
    name: "Salsa",
    aliases: "pico de gallo, fresh salsa, tomato salsa",
    category: "pantry",
    whyGood: "Veg + spice. Use on eggs and turkey.",
    whyAvoid: "Cheesy queso and creamy dips.",
    sortOrder: 710,
  },
  {
    name: "Vinegar",
    aliases: "apple cider vinegar, red wine vinegar, balsamic (small)",
    category: "pantry",
    whyGood: "Dressing base without bottled sugar.",
    whyAvoid: "Thick sweet bottled dressings.",
    sortOrder: 720,
  },
  {
    name: "Spices",
    aliases: "garlic powder, paprika, chili powder, salt, pepper, cumin, italian seasoning",
    category: "pantry",
    whyGood: "This is how lean protein tastes like dinner.",
    whyAvoid: "Packets with sugar and maltodextrin — read the back.",
    sortOrder: 730,
  },
];

export const GROCERY_CLEANSE_NOTE =
  "This is the 3-month cleanse list: very low carb, lean proteins. Bacon and extra-fatty cuts (ribeye, pork belly, 80/20, sausage) stay off. After you hit goal weight, a deep-desire meal can come back maybe once a month — not weekly.";
