-- Expand body measurements beyond weight-only check-ins.
ALTER TABLE "UserMeasurement" ADD COLUMN IF NOT EXISTS "neckIn" DOUBLE PRECISION;
ALTER TABLE "UserMeasurement" ADD COLUMN IF NOT EXISTS "shouldersIn" DOUBLE PRECISION;
ALTER TABLE "UserMeasurement" ADD COLUMN IF NOT EXISTS "chestIn" DOUBLE PRECISION;
ALTER TABLE "UserMeasurement" ADD COLUMN IF NOT EXISTS "waistIn" DOUBLE PRECISION;
ALTER TABLE "UserMeasurement" ADD COLUMN IF NOT EXISTS "hipsIn" DOUBLE PRECISION;
ALTER TABLE "UserMeasurement" ADD COLUMN IF NOT EXISTS "leftBicepIn" DOUBLE PRECISION;
ALTER TABLE "UserMeasurement" ADD COLUMN IF NOT EXISTS "rightBicepIn" DOUBLE PRECISION;
ALTER TABLE "UserMeasurement" ADD COLUMN IF NOT EXISTS "leftThighIn" DOUBLE PRECISION;
ALTER TABLE "UserMeasurement" ADD COLUMN IF NOT EXISTS "rightThighIn" DOUBLE PRECISION;
ALTER TABLE "UserMeasurement" ADD COLUMN IF NOT EXISTS "leftCalfIn" DOUBLE PRECISION;
ALTER TABLE "UserMeasurement" ADD COLUMN IF NOT EXISTS "rightCalfIn" DOUBLE PRECISION;
ALTER TABLE "UserMeasurement" ADD COLUMN IF NOT EXISTS "bodyFatPct" DOUBLE PRECISION;
ALTER TABLE "UserMeasurement" ADD COLUMN IF NOT EXISTS "source" TEXT NOT NULL DEFAULT 'member';
ALTER TABLE "UserMeasurement" ADD COLUMN IF NOT EXISTS "recordedByUserId" TEXT;

-- Notes may need more room (coach cues).
DO $$
BEGIN
  ALTER TABLE "UserMeasurement" ALTER COLUMN "notes" TYPE TEXT;
EXCEPTION
  WHEN others THEN NULL;
END $$;
