// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // For migrate / db push / studio use DIRECT_URL when available (Supabase
    // direct connection, port 5432). Falls back to DATABASE_URL (pooled ok for
    // many ops, but direct is safer for schema changes).
    url: (() => {
      const direct = process.env["DIRECT_URL"] ?? "";
      if (direct && !direct.includes("dummy")) return direct;
      return (
        process.env["POSTGRES_URL_NON_POOLING"] ??
        process.env["POSTGRES_PRISMA_URL"] ??
        process.env["POSTGRES_URL"] ??
        process.env["DATABASE_URL"] ??
        ""
      );
    })(),
  },
});
