// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // For migrate / db push / studio use DIRECT_URL when available (Supabase
    // direct connection, port 5432). Falls back to DATABASE_URL (pooled ok for
    // many ops, but direct is safer for schema changes).
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
