-- Portrait display crop (pan + zoom) for before / check-in photos.
ALTER TABLE "MemberProfile" ADD COLUMN IF NOT EXISTS "beforePhotoFocusX" DOUBLE PRECISION DEFAULT 50;
ALTER TABLE "MemberProfile" ADD COLUMN IF NOT EXISTS "beforePhotoFocusY" DOUBLE PRECISION DEFAULT 25;
ALTER TABLE "MemberProfile" ADD COLUMN IF NOT EXISTS "beforePhotoZoom" DOUBLE PRECISION DEFAULT 1;

ALTER TABLE "UserMeasurement" ADD COLUMN IF NOT EXISTS "photoFocusX" DOUBLE PRECISION DEFAULT 50;
ALTER TABLE "UserMeasurement" ADD COLUMN IF NOT EXISTS "photoFocusY" DOUBLE PRECISION DEFAULT 25;
ALTER TABLE "UserMeasurement" ADD COLUMN IF NOT EXISTS "photoZoom" DOUBLE PRECISION DEFAULT 1;
