ALTER TABLE "Program" ADD COLUMN IF NOT EXISTS "startDate" TEXT;

ALTER TABLE "ProgramDay" ADD COLUMN IF NOT EXISTS "calendarDate" TEXT;
ALTER TABLE "ProgramDay" ADD COLUMN IF NOT EXISTS "defaultSets" INTEGER;
ALTER TABLE "ProgramDay" ADD COLUMN IF NOT EXISTS "defaultReps" TEXT;
ALTER TABLE "ProgramDay" ADD COLUMN IF NOT EXISTS "defaultRestSec" INTEGER;
ALTER TABLE "ProgramDay" ADD COLUMN IF NOT EXISTS "publishedAt" TIMESTAMP(3);